version: '2'
services:
  api:
    build:
      context: ./api
      target: development
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - 5000:5000
    working_dir: /app
    stdin_open: true
    tty: true
    profiles:
      - full

  client:
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/build
    ports:
      - 3000:3000
    working_dir: /app
    stdin_open: true
    tty: true
    profiles:
      - full
