version: "2"
services:
  subscription:
    build:
      context: ./subscription
      target: production
    volumes:
      - ./subscription:/app
      - /app/node_modules
    ports:
      - 5000:5000
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - subscription_db
    networks:
      - subscriptions

  client:
    build:
      context: ./client
      target: production
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/build
    ports:
      - 3000:3000
    working_dir: /app
    stdin_open: true
    tty: true

  auth:
    build:
      context: ./auth
      target: production
    volumes:
      - ./auth:/app
      - /app/node_modules
    ports:
      - 5001:5001
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - users_db
    networks:
      - users

  subscription_db:
    image: mysql
    volumes:
      - /data/db
    environment:
      - MYSQL_ROOT_PASSWORD=asd
      - MYSQL_DATABASE=subscription_db
      - MYSQL_USER=chris1
      - MYSQL_PASSWORD=chrspasswd
    stdin_open: true
    tty: true
    networks:
      - subscriptions

  users_db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=asd
      - MYSQL_DATABASE=users
      - MYSQL_USER=chris
      - MYSQL_PASSWORD=chrspasswd
    networks:
      - users
    stdin_open: true
    tty: true

networks:
  users:
  subscriptions:
