version: "2"
services:
  api:
    build:
      context: ./api
      target: development
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - 5000:5000
    working_dir: /app
    stdin_open: true
    tty: true
    profiles:
      - full

  client:
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/build
    ports:
      - 3000:3000
    working_dir: /app
    stdin_open: true
    tty: true
    profiles:
      - full

  auth:
    build:
      context: ./auth
      target: development
    volumes:
      - ./auth:/app
      - /app/node_modules
    ports:
      - 5001:5001
    working_dir: /app
    stdin_open: true
    tty: true
    # depends_on:
    #   - db

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=asd
      - MYSQL_DATABASE=users
      - MYSQL_USER=chris
      - MYSQL_PASSWORD=chrspasswd
    profiles:
      - with_db
    # stdin_open: true
    # tty: true
